development:
  bin_path: /usr/local/bin
  searchd_binary_name: searchd
  client_timeout: 200
  morphology: stem_en
  min_infix_len: 4
production:
  bin_path: "/usr/bin"
  searchd_binary_name: "searchd"
  client_timeout: 200
  morphology: stem_en
  min_infix_len: 4
