development:
  # bin_path: /usr/local/bin
  bin_path: /usr/bin
  searchd_binary_name: searchd
  client_timeout: 200
  morphology: stem_en, soundex, metaphone
  dict: keywords
  min_infix_len: 1
  charset_table: "+,0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F"
  ignore_chars: "/,-"
  field_weights:
    product_family_name: 100
    product_name: 5
    product_description: 5
    software_name: 5
    software_description: 5
  attribute_weights:
    id: 100
  ngram_len: 1
  ngram_chars: U+3000..U+2FA1F
  mysql41: 9433
production:
  bin_path: "/usr/bin"
  searchd_binary_name: "searchd"
  client_timeout: 200
  morphology: stem_en, soundex, metaphone
  dict: keywords
  min_infix_len: 1
  charset_table: "+,0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F"
  ignore_chars: "/,-"
  field_weights:
    product_family_name: 100
    product_name: 5
    product_description: 5
    software_name: 5
    software_description: 5
  attribute_weights:
    id: 100
  ngram_len: 1
  ngram_chars: U+3000..U+2FA1F
  mysql41: 9433
test:
  mysql41: 9307
